// <auto-generated />
namespace HOPU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReadUserName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReadUserName));
        
        string IMigrationMetadata.Id
        {
            get { return "201812171225446_ReadUserName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
